language: cpp
git:
  depth: 3
sudo: false

matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, gfortran]
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - FC=gfortran-4.8
      - PYTHON=python

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, python3-pip, clang-3.4]
    env:
      - COMPILER=/usr/bin/clang++
      - PYTHON=python3

  - os: linux
    dist: xenial
    addons:
      apt:
        packages: [g++]
    env:
      - COMPILER=/usr/bin/g++
      - PYTHON=/bin/true

  - os: osx
    osx_image: xcode8.3
    compiler: clang
    env: COMPILER=clang++ PYTHON=python3
    before_install:
      - brew update
      - brew install $PYTHON || brew upgrade $PYTHON

# - os: osx
#   osx_image: xcode6.4
#   compiler: clang
#   env: COMPILER=clang++ PYTHON=python EXTRA_WFLAGS=-Wno-shorten-64-to-32

install:
- |
  $PYTHON -m pip --version || $PYTHON -m ensurepip --user
  $PYTHON -m pip install --user pybind11
  $PYTHON -c "import pybind11; print('headers: ' + pybind11.get_include(True))"
script:
  - $COMPILER --version
  - CXX=$COMPILER cmake .
  - make -j2
  - make check -j2
  - $PYTHON setup.py install --user --prefix=
  - $PYTHON -m unittest discover -v -s tests/
